In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep
import pandas as pd
import numpy as np
import re

In [25]:
def web_extraction():
    movie_names = []
    release_date = []
    description = []
    directors = []
    movie_stars = []
    ratings = []
    duration = []
    genre = []

    url = 'https://www.imdb.com/list/ls009668711/';
    pth = 'chromedriver.exe'

    driver = webdriver.Chrome(pth)

    driver.get(url)
    
    sleep(20)

    movies = 100
    for i in range(1,movies+1):
        
        movie = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/a')
                                    
        release = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/span[2]')

                                                 
        desc = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[2]')
                                                
        dire = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[3]/a[1]')

        rat = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/div[1]/div[1]/span[2]')

        dura = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[3]')

        gen = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[5]')
                                            
        movie_ = movie.text
        movie_names.append(movie_)
        
        whole = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[3]')
        whole_ = whole.text
        director, space, stars = whole_.partition('Stars: ')
        movie_stars.append(stars)
    
    
        release_ = release.text
        find_wo_brackets = release_.replace('(','')
        find_wo_brackets = find_wo_brackets.replace(')','')

        if i == 10:
            find_wo_brackets = 2004
        if i == 38:
            find_wo_brackets = 2015
        if i == 84:
            find_wo_brackets = 2006
        release_date.append(int(find_wo_brackets))

        description_ = desc.text
        description.append(description_)

        directors_ = dire.text
        directors.append(directors_)

        ratings_ = rat.text
        int_ratings_ = float(ratings_)
        ratings.append(int_ratings_)

        duration_ = dura.text
        durat, space, stri = duration_.partition(' ')
        int_duration = int(durat)
        duration.append(int_duration)

        genres_ = gen.text
        genre.append(genres_)

#########################################       SAVING IT INTO PANDAS DATAFRAME        #######################################################################
  
    data = {'Movies':movie_names,'Release Date':release_date,'Directors':directors,'Movie Stars':movie_stars,'Duration (in mins)':duration,'Ratings':ratings,'Genre':genre,'Description':description}

    df = pd.DataFrame(data)
    df.to_csv('drama_imdb.csv')
    return df
web_extraction()

,Movies,Release Date,Directors,Movie Stars,Duration (in mins),Ratings,Genre,Description
0,The Godfather,1972,Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Diane Ke...",175,9.2,"Crime, Drama",The aging patriarch of an organized crime dyna...
1,The Godfather: Part II,1974,Francis Ford Coppola,"Al Pacino, Robert De Niro, Robert Duvall, Dian...",202,9.0,"Crime, Drama",The early life and career of Vito Corleone in ...
2,The Dark Knight,2008,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",152,9.0,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...
3,Pulp Fiction,1994,Quentin Tarantino,"John Travolta, Uma Thurman, Samuel L. Jackson,...",154,8.9,"Crime, Drama","The lives of two mob hitmen, a boxer, a gangst..."
4,Heat,1995,Michael Mann,"Al Pacino, Robert De Niro, Val Kilmer, Jon Voight",170,8.2,"Action, Crime, Drama",A group of high-end professional thieves start...
...,...,...,...,...,...,...,...,...
95,La La Land,2016,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",128,8.0,"Comedy, Drama, Music","While navigating their careers in Los Angeles,..."
96,A Clockwork Orange,1971,Stanley Kubrick,"Malcolm McDowell, Patrick Magee, Michael Bates...",136,8.3,"Crime, Sci-Fi","In the future, a sadistic gang leader is impri..."
97,The Shape of Water,2017,Guillermo del Toro,"Sally Hawkins, Octavia Spencer, Michael Shanno...",123,7.3,"Drama, Fantasy, Romance",At a top secret research facility in the 1960s...
98,JFK,1991,Oliver Stone,"Kevin Costner, Gary Oldman, Jack Lemmon, Walte...",189,8.0,"Drama, History, Thriller",New Orleans District Attorney Jim Garrison dis...
99,Prisoners,2013,Denis Villeneuve,"Hugh Jackman, Jake Gyllenhaal, Viola Davis, Me...",153,8.1,"Crime, Drama, Mystery",When Keller Dover's daughter and her friend go...

In [27]:
df_new = pd.read_csv('drama_imdb.csv')
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          100 non-null    int64
 1   Movies              100 non-null    object
 2   Release Date        100 non-null    int64
 3   Directors           100 non-null    object
 4   Movie Stars         100 non-null    object
 5   Duration (in mins)  100 non-null    int64
 6   Ratings             100 non-null    float64
 7   Genre               100 non-null    object
 8   Description         100 non-null    object
dtypes: float64(1), int64(3), object(5)
memory usage: 7.2+ KB

In [28]:
df_new.sort_values(by='Release Date',ascending=True)

,Unnamed: 0,Movies,Release Date,Directors,Movie Stars,Duration (in mins),Ratings,Genre,Description
68,68,Gone with the Wind,1939,Victor Fleming,"Clark Gable, Vivien Leigh, Thomas Mitchell, Ba...",238,8.1,"Drama, History, Romance",The manipulative daughter of a Georgia plantat...
72,72,Citizen Kane,1941,Orson Welles,"Orson Welles, Joseph Cotten, Dorothy Comingore...",119,8.3,"Drama, Mystery",Following the death of publishing tycoon Charl...
89,89,Casablanca,1942,Michael Curtiz,"Humphrey Bogart, Ingrid Bergman, Paul Henreid,...",102,8.5,"Drama, Romance, War",A cynical expatriate American cafe owner strug...
22,22,Stalag 17,1953,Billy Wilder,"William Holden, Don Taylor, Otto Preminger, Ro...",116,8.0,"Comedy, Drama, War",After two Americans are killed while escaping ...
62,62,On the Waterfront,1954,Elia Kazan,"Marlon Brando, Karl Malden, Lee J. Cobb, Rod S...",108,8.1,"Crime, Drama, Thriller",An ex-prize fighter turned New Jersey longshor...
...,...,...,...,...,...,...,...,...,...
95,95,La La Land,2016,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",128,8.0,"Comedy, Drama, Music","While navigating their careers in Los Angeles,..."
97,97,The Shape of Water,2017,Guillermo del Toro,"Sally Hawkins, Octavia Spencer, Michael Shanno...",123,7.3,"Drama, Fantasy, Romance",At a top secret research facility in the 1960s...
66,66,"Three Billboards Outside Ebbing, Missouri",2017,Martin McDonagh,"Frances McDormand, Woody Harrelson, Sam Rockwe...",115,8.1,"Comedy, Crime, Drama",A mother personally challenges the local autho...
60,60,Green Book,2018,Peter Farrelly,"Viggo Mortensen, Mahershala Ali, Linda Cardell...",130,8.2,"Biography, Comedy, Drama",A working-class Italian-American bouncer becom...
20,20,Once Upon a Time... In Hollywood,2019,Quentin Tarantino,"Leonardo DiCaprio, Brad Pitt, Margot Robbie, E...",161,7.6,"Comedy, Drama",A faded television actor and his stunt double ...

In [32]:
import matplotlib.pyplot as plt